const UK = {
  0: ['', ''],
  1: ['перший', 'один'],
  2: ['second', 'two'],
  3: ['третій', 'три'],
  4: ['четвертий', 'чотири'],
  5: ["п'ятий", "п'ять"],
  6: ['sixth', 'six'],
  7: ['seventh', 'сім'],
  8: ['восьмий', 'вісім'],
  9: ["дев'ятий", 'nine'],
  10: ['десятий', 'ten'],
  11: ['одинадцятий', 'eleven'],
  12: ['twelfth', 'twelve'],
  13: ['thirteenth', 'thirteen'],
  14: ['чотирнадцятий', 'fourteen'],
  15: ["п'ятнадцятий", 'fifteen'],
  16: ['sixteenth', 'sixteen'],
  17: ['seventeenth', 'seventeen'],
  18: ['eighteenth', 'eighteen'],
  19: ['nineteenth', 'nineteen'],
  20: ['двадцятий', 'twenty'],
  30: ['тридцятий', 'thirty'],
  40: ['сороковий', 'сорок'],
  50: ['fiftieth', 'fifty'],
  60: ['sixtieth', 'sixty'],
  70: ['seventieth', 'seventy'],
  80: ['eightieth', 'eighty'],
  90: ["дев'яностий", 'ninety'],
  100: ['сотий', 'сто'],
  levels: [
    ['', ''],
    ['тисячний', 'thousand'],
    ['мільйонний', 'мільйон'],
    ['мільярдний', 'мільярд'],
    ['трильйонний', 'трильйон'],
  ],
};

export default UK;
